### ISSUE TITLE
function for random email id

### ISSUE THREAD

**Issue by akulsr0** [akulsr0/random-in#3]
### CONTRIBUTION GUIDE

- Fork the repo
- clone the forked repo on your machine and start coding
- create a file in src folder as email.ts
- write a function which returns random email address and export it
- import the function in index.ts file and export that function as getRandomEmail name

In src/email.ts

```
export const getRandomEmail = () => {
    ...your code here
    ....return random email
}
```
In index.ts
```
import { getRandomEmail } from './src/email';

module.exports.getRandomEmail = (): string => {
    return getRandomEmail();
}
```
After this, you can continue to raise a PR

**Comment by meghnavarma0** [comment]
Done! I have raised a PR
