### ISSUE TITLE
get random programming language

### ISSUE THREAD

**Issue by akulsr0** [akulsr0/random-in#9]
- Create a file in random-in/src, named as programming.ts
- Export a function named as getRandomProgrammingLanguage() from random-in/src/programming.ts
- If you need to create an array of programming languages, create a file inside random-in/utils, named as programming.ts. Then export the array from there and import it in random-in/src/programming.ts
- Import that function in random-in/index.ts, and export from there
- Make a PR 👍 

Also, starring the repo would be highly appreciated  :)

**Comment by harin49** [comment]
Hi, @akulsr0. Can I work on this issue ?

**Comment by akulsr0** [comment]
Sure!

**Comment by harinj49** [comment]
@akulsr0  any steps to run the implementation locally?
